name: Update task
description: File a task to update an existing `buddypress/docs` Documentation resource.
title: "[Update]: "
projects: ["buddypress/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this task to update an existing Documentation page of one of the `buddyress/docs` handbooks!
  - type: input
    id: ghLink
    attributes:
      label: Link to the existing GH Documentation page.
      description: This will be useful to identify & reach the page to update.
      placeholder: https://github.com/buddypress/buddypress/docs/
    validations:
      required: true
  - type: textarea
    id: what-needs-to-be-updated
    attributes:
      label: What needs to be updated?
      description: What are the needed changes (text, screenshots,...)?
      placeholder: This is what needs to be updated!
      value: "Let's update..."
    validations:
      required: true
  - type: dropdown
    id: handbook
    attributes:
      label: Handbook of the page to update
      description: Select the GH Handbook you think the page should be available in.
      options:
        - buddypress/docs (Docs root)
        - buddypress/docs/user
        - buddypress/docs/developer
        - buddypress/docs/contributor
      default: 1
    validations:
      required: true
  - type: checkboxes
    id: taskTracker
    attributes:
      label: Tasks to accomplish
      description: This is a reminder about steps needed for this Documentation resource to be updated.
      options:
        - label: This task has been added to the "Todo" panel of the Documentation project.
          required: false
        - label: A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
          required: false
        - label: The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.
          required: false